version: '2'

services:
    balancer:
        environment:
            - PORT=34000
        build:
            context: ./Balancer
            dockerfile: Dockerfile
        container_name: balancer
        ports:
            - "34000:4567"
        links:
            - logservice1
            - logservice2
            - logservice3

    logservice1:
        environment:
            - PORT=34001
        build:
            context: ./LogService
            dockerfile: Dockerfile
        container_name: logservice1
        links:
            - db
    
    logservice2:
        environment:
            - PORT=34002
        build:
            context: ./LogService
            dockerfile: Dockerfile
        container_name: logservice2
        links:
            - db
    
    logservice3:
        environment:
            - PORT=34003
        build:
            context: ./LogService
            dockerfile: Dockerfile
        container_name: logservice3
        links:
            - db
    
    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        command: mongod
        
volumes:
    mongodb:
    mongodb_config: